### ISSUE TITLE
Issues with margins and logo/grid placement

### ISSUE THREAD

**Issue by mato0039** [mato0039/components-on-a-grid#1]
Hi Chelle, 

I am having issues with the logo placement. I put it in grid-row: 2 but it goes underneath the header img. 

I also can't figure out the margins. Should they go around the img or the figure?

Thanks, 

Cathy

@hellachella

**Comment by mato0039** [comment]
@JessJodoin

**Comment by hellachella** [comment]
Was this resolved?

**Comment by hellachella** [comment]
If not, ping me on Slack. Sorry I missed this.

**Comment by JessJodoin** [comment]
Was this issue resolved?
